name: transaction-app

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - transaction-app

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - transaction-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  frontent:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - transaction-app
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host
    depends_on:
      - api

  # caddy:
  #   image: caddy:2.9-alpine
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   networks:
  #     - transaction-app
  #   depends_on:
  #     - frontent
  #     - api

volumes:
  mongo_data:
  # caddy_data:
  # caddy_config:
networks:
  transaction-app:
    driver: bridge
